const questions_json = {
    nodes: [
        {index: 0, label: "מה המגדר שלך?", field: "gender"},
        {index: 1, label: "האם יש לך ילדים מתחת לגיל 18?", field: "kids under 18"},
        {index: 2, label: "האם יש לך ילדים מתחת לגיל 5?", field: "kids under 5"},
        {index: 3, label: "מה גובה שכר הברוטו החודשי שלך?", field: "salary"},
        {index: 4, label: "האם לך או לבן.ת הזוג היה עסק ב- 6 השנים האחרונות (משנת 2014)?", field: "business"},
        {index: 5, label: "האם עבדת אצל אותו מעסיק ב-6 השנים האחרונות (משנת 2014)?", field: "same employer"},
        {index: 6, label: "האם הגשת החזר מס עבור 6 השנים האחרונות (משנת 2014)?", field: "tax return"},
        {index: 20, label: "האם שילמת מס עבור פדיון מוקדם של קופת גמל, ביטוח חיים, קרן פנסיה או קרן השתלמות?", field: "fund"},
        {index: 21, label: "האם היו לך הכנסות ממספר מקומות במקביל?", field: "multiple incomes"},
        {index: 22, label: "האם ביצעת עסקה במקרקעין ושילמת מס שבח?", field: "real estate with tax"},
        {index: 23, label: "האם יש לך פעילות בניירות ערך אשר שילמת עבורה מס?", field: "stock exchange"},
        {index: 100, label: "הינך בעל סיכוי נמוך לקבלת החזר מס"},
        {index: 200, label: "יש לך סיכוי גבוה לקבלת החזר מס!"}
    ],
    edges: [
        {from: 0, to: 2, label: "זכר"},
        {from: 0, to: 1, label: "נקבה"},
        {from: 1, to: 2, label: "לא"},
        {from: 1, to: 2, label: "1"},
        {from: 1, to: 2, label: "2+"},
        {from: 2, to: 3, label: "לא"},
        {from: 2, to: 3, label: "1"},
        {from: 2, to: 3, label: "2+"},
        {from: 3, to: 20, label: 'עד 7000 ש"ח', eligible: false},
        {from: 3, to: 4, label: '7000-10000 ש"ח'},
        {from: 3, to: 4, label: '7000-15000 ש"ח'},
        {from: 3, to: 4, label: 'מעל 15000 ש"ח'},
        {from: 4, to: 5, label: "כן, בחלקן"},
        {from: 4, to: 20, label: "כן, בכולן", eligible: false},
        {from: 4, to: 5, label: "לא"},
        {from: 5, to: 20, label: "כן", eligible: false},
        {from: 5, to: 6, label: "לא"},
        {from: 6, to: 20, label: "כן, בחלקן"},
        {from: 6, to: 20, label: "כן, בכולן", eligible: false},
        {from: 6, to: 20, label: "לא"},
        {from: 20, to: 21, label: "כן", eligible: true},
        {from: 20, to: 21, label: "לא"},
        {from: 21, to: 22, label: "כן", eligible: true},
        {from: 21, to: 22, label: "לא"},
        {from: 22, to: 23, label: "כן", eligible: true},
        {from: 22, to: 23, label: "לא"},
        {from: 23, to: 100, label: "כן", eligible: true},
        {from: 23, to: 100, label: "לא"},
    ]
};

export default questions_json;
